In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3,4],
              [2,2,2,2],
              [3,3,3,3]],dtype=np.float32)

d = np.array([[11,12],
              [21,22],
              [31,32]],dtype=np.float32)
# for b in range(len(self.X)):
m,n=len(d[0]),len(x[0])
DCDW = np.zeros((n,m))
for b in range(len(x)):
    for i in range(m):
        for ii in range(n):
            DCDW[ii,i] +=x[b,ii]*d[b,i]
print(DCDW)

DCDW = np.zeros((n,m))
for b in range(len(x)):
    DCDW += np.outer(x[b,:],d[b,:])
print(DCDW)

i=0
ii=0
for i in d:
    print(i)
    ii += i
print(ii)
print(np.sum(d,axis=0))

[[146. 152.]
 [157. 164.]
 [168. 176.]
 [179. 188.]]
[[146. 152.]
 [157. 164.]
 [168. 176.]
 [179. 188.]]
[11. 12.]
[21. 22.]
[31. 32.]
[63. 66.]
[63. 66.]


In [3]:
foo = np.ones((2,3,4,5))
baz = np.array([1,2,3,4,5])

bar = np.sum(foo,axis=(0,1,2))
print(bar.shape)
print(bar+baz)
print(foo+baz)


(5,)
[25. 26. 27. 28. 29.]
[[[[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]

  [[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]

  [[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]]


 [[[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]

  [[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]

  [[2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]
   [2. 3. 4. 5. 6.]]]]
